---
id: pushchain
name: Push Chain - Universal Blockchain Tutorial
summary: Learn how to build universal blockchain applications that you can deploy once and reach any blockchain (EVM or non-EVM) simultaneously.
level: 1
tags:
  - JS
  - Remix
  - PushChain
steps:
  - name: Welcome to Push Chain
    path: 0-welcome
  - name: Core Concepts
    path: 1-core-concepts
  - name: Deploy Contracts on Push Chain
    path: 2-deploy-contracts
  - name: Send Universal Transaction to Simple Counter Contract
    path: 3-send-universal-transaction
  - name: Universal Account Discovery with Solidity
    path: 4-contract-helpers-solidity
  - name: JavaScript Account Conversion Helpers
    path: 5-utility-functions-js
  - name: Universal Counter Smart Contract
    path: 7-universal-counter-solidity
  - name: Conclusion
    path: 8-conclusion
